import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

type Props = {
  timestamp: string;
  url: string;
};

const Home: NextPage<Props> = ({ timestamp, url }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h2>Timestamp: {timestamp}</h2>
        <h3>Timestamp: {url}</h3>
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const timestamp = new Date().toLocaleString();

  const url = process.env.URL;

  return {
    props: {
      timestamp,
      url,
    },
    revalidate: 60,
  };
}

export default Home;
